name: Publish release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Name of release
        required: true
      publish:
        type: boolean
        description: Would release be published
        required: true
        default: true
      draft:
        type: boolean
        description: Publish draft first
        required: true
        default: true

jobs:
  build:
    name: Create artifacts from master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          distribution: adopt
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar

      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: build/libs

      - name: Create release
        if: ${{ github.event.inputs.publish }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "v${{ github.event.inputs.version }}"
          draft: ${{ github.event.inputs.draft }}
          files: |
            artifacts/*.jar
